name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile --prefer-offline
      - uses: actions/cache@v3
        with:
          key: playwright-bin
          path: ~/.cache/ms-playwright
      - run: pnpm playwright install chromium
      - run: pnpm ci
      - uses: ArnaudBarre/npm-publish@v1.3
        if: ${{ contains(github.event.head_commit.message, '[publish]') && github.ref == 'refs/heads/main' }}
        with:
          working-directory: dist
          npm-token: ${{ secrets.NPM_TOKEN }}
