name: Publish to npm
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[publish]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - run: pnpm install --frozen-lockfile
      - run: pnpm ci
      - uses: ArnaudBarre/npm-publish@v1.1
        with:
          working-directory: dist
          npm-token: ${{ secrets.NPM_TOKEN }}
